name: edu_connect
description: A  Flutter application, which enables Tutors and parents/Students to interact with each others. 


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_splash_screen: ^3.0.1
  lottie: ^0.7.0+1
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.3
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.0
  curved_navigation_bar: ^0.3.4
  shared_preferences: ^0.5.12+4
  image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: image_picker_workaround
      path: packages/image_picker/image_picker
  firebase_storage: ^5.2.0
  geolocator: ^6.1.13






  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - lib/assets/animations/lotties/welcome_welcome.json
    - lib/assets/animations/lotties/welcome_email.json
    - lib/assets/animations/lotties/welcome_confused.json
    - lib/assets/animations/lotties/swipe_left.json
    - lib/assets/userData/defaultUserAvatar.png
    - lib/assets/UI_pictures/subject_icons/


  # To add custom assets.fonts to your application, add a assets.fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "assets.fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # assets.fonts:
  #   - family: Schyler
  #     assets.fonts:
  #       - asset: assets.fonts/Schyler-Regular.ttf
  #       - asset: assets.fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     assets.fonts:
  #       - asset: assets.fonts/TrajanPro.ttf
  #       - asset: assets.fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
assets.fonts:
  - family: AlfaSlabOne
    assets.fonts:
      - asset: lib/assets/fonts/AlfaSlabOne-Regular.ttf